apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  labels:
    app: sonarqube
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
